defmodule LemonadeStand.Repo.Migrations.AddResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:parts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    create table(:components, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :part_id,
        references(:parts,
          column: :id,
          name: "components_part_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:component_substitutes, primary_key: false) do
      add(
        :component_id,
        references(:components,
          column: :id,
          name: "component_substitutes_component_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )

      add(
        :part_id,
        references(:parts,
          column: :id,
          name: "component_substitutes_part_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )
    end
  end

  def down do
    drop(constraint(:component_substitutes, "component_substitutes_component_id_fkey"))

    drop(constraint(:component_substitutes, "component_substitutes_part_id_fkey"))

    drop(table(:component_substitutes))

    drop(constraint(:components, "components_part_id_fkey"))

    drop(table(:components))

    drop(table(:parts))
  end
end
